### ISSUE TITLE
Add property-based tests for `BiMap`

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#119]
I would like to have `hedgehog` roundript tests for our `BiMap` because now they contain non-trivial logic.

**Comment by jiegillet** [comment]
I've been working on this, and I have an interesting problem. 
My test `tripping x (forward bimap) (join . fmap (backward bimap))` for `_Double` fails, because apparently
```
ghci> 0/0 == (0/0 :: Double)
False
```
What to do? :)

**Comment by ChShersh** [comment]
@jiegillet Trick with `isNan` is used for `Eq` instance for `Value` as well:

* https://github.com/kowainik/tomland/blob/f7ac2946505ad154ac087044ee30051b1399684b/src/Toml/Type/Value.hs#L127-L135

I guess it's okay to violate semantic for `NaN` in our case.
