### ISSUE TITLE
Support array of tables

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#13]
This is important issue since array of tables is probably the only reasonable way to specify data structures like `List` and `Map` in TOML. Though, it's hard to support them...

**Comment by GooseDB** [comment]
If you need https://github.com/toml-lang/toml#user-content-array and https://github.com/toml-lang/toml#user-content-table I can take this issue.

**Comment by GooseDB** [comment]
If you need [arrays](https://github.com/toml-lang/toml#user-content-array) and [tables](https://github.com/toml-lang/toml#user-content-table) I can take this issue.

**Comment by ChShersh** [comment]
@GooseDB Arrays and tables are already supported by the `tomland` library :slightly_smiling_face: This issue is about [Array of tables](https://github.com/toml-lang/toml#user-content-array-of-tables).

**Comment by GooseDB** [comment]
Oh, I see. I'll try.

**Comment by ChShersh** [comment]
@GooseDB Note, that you should uncomment and use this field of `TOML` data type:

* https://github.com/kowainik/tomland/blob/044de639b8c34285f24e244378c9116b0a86b7e6/src/Toml/Type/TOML.hs#L24

Also, be aware that the refactoring of the `Toml.Parser` module by @MorrisLaw is coming and it's probably a good idea to wait some time to avoid huge conflicts :slightly_smiling_face:

**Comment by GooseDB** [comment]
@ChShersh So, when will the refactoring be completed?

**Comment by ChShersh** [comment]
@GooseDB I think, only @MorrisLaw can answer...

**Comment by ChShersh** [comment]
@GooseDB On the other hand, I think, you can start to work in this. I will help with resolving conflicts if anything happens 👍

**Comment by gahag** [comment]
I've sent a pull request with the refactoring.

**Comment by jiegillet** [comment]
I might start working on this one if it's OK.

**Comment by jiegillet** [comment]
I have a version that seems to be working (I need to run more tests though), but it doesn't include the new parsers in #121 so I'll wait for that one to be merged to proceed.
