### ISSUE TITLE
Road to Arrays of Tables - Including arrays into TOML

### ISSUE THREAD

**Issue by jiegillet** [kowainik/tomland#131]
Uncommenting `tomlTableArrays` in 

```haskell
data TOML = TOML
    { tomlPairs  :: HashMap Key AnyValue
    , tomlTables :: PrefixMap TOML
--    , tomlTableArrays :: HashMap Key (NonEmpty TOML)
    } deriving (Show, Eq)
```
and getting everything to compile.

**Comment by jiegillet** [comment]
@ChShersh question for this one. The example in `Edsl.hs` says:
```haskell
exampleToml :: TOML
exampleToml = mkToml $ do
    \"key1\" =: 1
    \"key2\" =: Bool True
    table \"tableName\" $
        \"tableKey\" =: Array [\"Oh\", \"Hi\", \"Mark\"]
```
but a key will cannot be created that easily. 
Should I add some kind of
```haskell
mkKey :: Text -> Key
mkDottedKey :: NonEmpty Text -> Key
```

**Comment by jiegillet** [comment]
Actually I have a question, why use `NonEmpty TOML` rather than `[TOML]`?
I think the toml file `[[a]]` is valid, and there is no element in the array.

**Comment by ChShersh** [comment]
@jiegillet Toml file with content `[[a]]` can be represented as:

```haskell
mempty 
    { tomlArrayTables = fromList 
        [ ("a" , mempty :| [])
        ]
    }
```

`mempty :: TOML` is associated with key `a`.

**Comment by ChShersh** [comment]
@jiegillet It wouldn't, because how would you distinguish:

```toml
[[a]]
```

from

```toml
[[a]]
[[a]]
```

?

The last one is semantically two objects.

**Comment by jiegillet** [comment]
Good point ^^
