### ISSUE TITLE
`<$>` and `<*>` operators do not render properly on hackage

### ISSUE THREAD

**Issue by jiegillet** [kowainik/tomland#139]
[See the example at `dimap`.](http://hackage.haskell.org/package/tomland-0.5.0/docs/Toml-Bi-Monad.html)

They seem to be treat `<$>` as a reference/link to `$`.

**Comment by ChShersh** [comment]
@jiegillet Thanks for the keeping track of the issue! I'm aware of this and I was planning to walk through whole documentation and fix it.

Meanwhile we all can read this blog post:

* https://artyom.me/haddock-mistakes

**Comment by ChShersh** [comment]
This is already fixed in `master`.
