### ISSUE TITLE
Support array of inline tables

### ISSUE THREAD

**Issue by jiegillet** [kowainik/tomland#145]
Add parser + tests for inline tables

**Comment by ChShersh** [comment]
This issue is not urgent. Just a syntactic sugar. Inline tables are already supported, but not in a context of array of tables. But let's implement array of tables first, and only then we can think about array of inline tables.

**Comment by jiegillet** [comment]
Sure thing, I've had working code for a while, and this issue was always meant to be tackled after arrays of tables.
