### ISSUE TITLE
Implement better generator for key `Piece`

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#177]
Currently generator for `Piece` just generates simple bare keys.

https://github.com/kowainik/tomland/blob/90af0bdacf81ffe5a156d214da10dc0568bf1f6f/test/Test/Toml/Gen.hs#L107-L108

But what it should do:

1. Generate bare keys with ASCII letters, ASCII digits, underscores, and dashes (`A-Za-z0-9_-`)
2. Generate quoted keys (both basic and literal strings) with unicode inside.

This may take quite some time and effort to implement such generator, so putting it into separate issue.

**Comment by cronokirby** [comment]
I believe this is resolved as of: https://github.com/kowainik/tomland/pull/184
