### ISSUE TITLE
Support custom sorting of keys during pretty-printing

### ISSUE THREAD

**Issue by chshersh** [kowainik/tomland#189]
Sorting is done via `PrintOptions`:

https://github.com/kowainik/tomland/blob/e7f36914311e6c1fe50ed50606c4fe9b2ed8aef6/src/Toml/Printer.hs#L27-L31

However, custom sorting of keys is not supported. In order to support it this data type should be generalised as follows:

```haskell
data PrintOptions = PrintOptions
    { printOptionsSorting :: !(Maybe (Key -> Key -> Ordering))
    , printOptionsIndent  :: !Int
    } 
```

Couple notes:

1. Fields are renamed according to our style guide.
2. Fields are strict now to make code more robust.
3. Instead of boolean flag we now have optional comparison function.

cc @ramanshah

**Comment by ramanshah** [comment]
Thanks so much for the writeup (and pointers)! This is exactly the enhancement I was interested in. I'd be happy to try implementing this or helping any way that I can. Let me know.

**Comment by chshersh** [comment]
@ramanshah Sure, feel free to work on that issue! I described the beginning of the implementation. Let us know if something is not clear :slightly_smiling_face:

**Comment by ramanshah** [comment]
On it! Talk soon :)

**Comment by ramanshah** [comment]
I'm a little stuck with the build system. This is on Mac OS X Sierra 10.12.6.

```
master ~/tomland> stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
master ~/tomland> stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
master ~/tomland> cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
master ~/tomland> stack build
Unable to parse cabal file ~/tomland/tomland.cabal

- 0:0: Unsupported cabal-version. See https://github.com/haskell/cabal/issues/4899.

exit 1
```

I've tried to Google my way out of this at some length but am still stumped. Any pointers? I'd be happy to update `CONTRIBUTING.md` if there's some prerequisite step that newcomers may not know to do.

**Comment by ramanshah** [comment]
Just figured it out! I learned that the relevant `cabal` (library) is baked into the `stack` version. Running `stack upgrade` to bump my `stack` to 1.9.3 got me a clean build and passing test suite.

Is there a good place to annotate this dependency?

**Comment by ramanshah** [comment]
Note from a first attempt: implementing `PrintOptions` as above and making appropriate changes to `defaultOptions` and `mapOrdered`, the following breaks in `prettyTables`:

```
~/tomland/src/Toml/Printer.hs:131:31: error:
    • Couldn't match type ‘Piece’ with ‘Key’
      Expected type: PrefixMap TOML -> [Text]
        Actual type: HashMap Key (PrefixTree TOML) -> [Text]
    • In the expression: mapOrdered (prettyTable . snd) options
      In an equation for ‘prettyTables’:
          prettyTables options i pref
            = mapOrdered (prettyTable . snd) options
            where
                prettyTable :: PrefixTree TOML -> [Text]
                prettyTable (Leaf k toml)
                  = let ...
                    in
                      ""
                        : tabWith options i <> prettyTableName name
                            : dropWhile (== "") (prettyTomlInd options (i + 1) name toml)
                prettyTable (Branch k mToml prefMap)
                  = let ...
                    in
                      ""
                        : tabWith options i <> prettyTableName name
                            : dropWhile
                                (== "") (toml ++ prettyTables options nextI name prefMap)
                prettyTableName :: Text -> Text
                prettyTableName n = "[" <> n <> "]"
    |
131 | prettyTables options i pref = mapOrdered (prettyTable . snd) options
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'll study the codebase more deeply in a few days when I have some more discretionary time. In the meantime, any extra pairs of eyes are extremely helpful!

**Comment by chshersh** [comment]
@ramanshah 

> Running stack upgrade to bump my stack to 1.9.3 got me a clean build and passing test suite.

I'm currently using `stack-1.9.3` as well, this is the latest version, so everything should work with this version without any problems 🙂 All our projects are built on Travis CI with the latest versions of both `cabal-install` and `stack` to make sure that they can be built with both build tools.

> I'll study the codebase more deeply in a few days when I have some more discretionary time. In the meantime, any extra pairs of eyes are extremely helpful!

I'm not sure what exact changes did you make to `mapOrdered` so I can't understand the problem from this type error. But the idea is that if `PrintOptions` have `Nothing` then you shouldn't change the order of keys. If it's `Just comparator` then you should sort with the `sortBy` function and passing given comparator.

**Comment by ramanshah** [comment]
Here's what I think is going on. `prettyTables` pretty-prints table arrays based on sorting `Piece`s:

```
prettyTables :: PrintOptions -> Int -> Text -> PrefixMap TOML -> [Text]

-- via
type PrefixMap a = HashMap Piece (PrefixTree a) 
```

But `prettyTableArrays` does so based on sorting `Key`s:

```
prettyTableArrays :: PrintOptions -> Int -> Text -> HashMap Key (NonEmpty TOML) -> [Text]
```

The existing `mapOrdered`, taking just the boolean `shouldSort`, takes advantage of the polymorphic `sortOn` to handle both cases:

```
-- Returns a proper sorting function
mapOrdered :: Ord k => ((k, v) -> [t]) -> PrintOptions -> HashMap k v -> [t]
mapOrdered f options
    | shouldSort options = concatMap f . sortOn fst . HashMap.toList
    | otherwise          = concatMap f . HashMap.toList

-- via
sortOn :: Ord b => (a -> b) -> [a] -> [a]
```

My current attempt at `mapOrdered` needs to be more specialized to compile with a more explicit `Maybe (Key -> Key -> Ordering)` custom comparator:

```
-- Returns a proper sorting function
mapOrdered :: ((Key, v) -> [t]) -> PrintOptions -> HashMap Key v -> [t]
mapOrdered f options = case (printOptionsSorting options) of
    Just sorter -> concatMap f . sortBy (applyToFirst sorter) . HashMap.toList
    Nothing     -> concatMap f . HashMap.toList

-- Compares pairs of tuples by their first elements with a custom sorter
applyToFirst :: Ord a => (a -> a -> Ordering) -> (a, b) -> (a, b) -> Ordering
applyToFirst sorter x y = sorter (fst x) (fst y)

-- via
data PrintOptions = PrintOptions
    { printOptionsSorting :: !(Maybe (Key -> Key -> Ordering))  -- ^ should table keys be sorted or not
    , printOptionsIndent  :: !Int   -- ^ indentation size
    }
```

But then `prettyTable` breaks. If I understand correctly, I'm seeking guidance in what you think would be a good type signature for `printOptionsSorting`. Since `printOptionsSorting` will be part of the public API, I definitely want your input before cutting in more deeply. Thanks!

**Comment by chshersh** [comment]
@ramanshah Hmm, it's hard to keep track of everything here now... Could you try to open Pull Request and I can review it? It will also help me to see the context clearer :slightly_smiling_face:

**Comment by ramanshah** [comment]
Done - interested to hear your thoughts. Thanks :)
