### ISSUE TITLE
Add combinators `set / hashSet` for array of tables

### ISSUE THREAD

**Issue by chshersh** [kowainik/tomland#201]
Currently, we have `list` and `nonEmpty` combinators for coding array of tables. It would be nice to have `set` and `hashSet` as well.

**Comment by SanchayanMaity** [comment]
@chshersh I did like to help with this.

**Comment by chshersh** [comment]
@SanchayanMaity Sure, go for it :+1:

**Comment by SanchayanMaity** [comment]
@chshersh  Can you point me in the right direction a bit?

set :: forall a . TomlCodec a -> Key -> TomlCodec (Set a)
hashSet :: forall a . TomlCodec a -> Key -> TomlCodec (HashSet a)

Looking at the existing code, would the above be the correct type signatures? The initial thought I had for *set* was to mimic the *list* implementation but instead of fmapping toList, map (fromList . toList) however this fails the Ord constraint required for *Set*. Not sure if I am on the right train of thought.

**Comment by chshersh** [comment]
@SanchayanMaity You're in the right direction :+1: The types of `set` and `hashSet` along with the implementation are correct. You only need to add required constraints as compiler tells you. So for `set` the type signature will look like this:

```haskell
set :: forall a . Ord a => TomlCodec a -> Key -> TomlCodec (Set a)
```

If you want to put elements in the `Set` container, you need to be able to compare them.

**Comment by SanchayanMaity** [comment]
@chshersh 

```haskell
set :: forall a . Ord a => TomlCodec a -> Key -> TomlCodec (Set a)
set codec key = Codec
    { codecRead = ((Set.fromList . toList) <$> codecRead nonEmptyCodec) `catchError` \case
        TableNotFound errKey | errKey == key -> pure Set.empty
        err -> throwError err
    , codecWrite = \as -> do
        let tomls = (Set.fromList . toList) $ fmap (execTomlCodec codec) ((NE.fromList . Set.toList) as)
        mTables <- gets $ HashMap.lookup key . tomlTableArrays

        let newTomls = case mTables of
                Nothing       -> tomls
                Just oldTomls -> ((Set.fromList . toList) oldTomls) <> tomls

        as <$ modify (insertTableArrays key ((NE.fromList . Set.toList) newTomls))
    }
  where
    nonEmptyCodec :: TomlCodec (NonEmpty a)
    nonEmptyCodec = nonEmpty codec key
```

I came up with this which does not look clean and fails to compile. What stymies me is the error.

```haskell
home/sanchayan/GitSources/tomland/src/Toml/Bi/Combinators.hs:297:22: error:
    • Could not deduce (Ord TOML) arising from a use of ‘Set.fromList’
      from the context: Ord a
        bound by the type signature for:
                   set :: forall a. Ord a => TomlCodec a -> Key -> TomlCodec (Set a)
        at src/Toml/Bi/Combinators.hs:291:1-66
    • In the first argument of ‘(.)’, namely ‘Set.fromList’
      In the expression: (Set.fromList . toList)
      In the expression:
        (Set.fromList . toList)
          $ fmap (execTomlCodec codec) ((NE.fromList . Set.toList) as)
    |
297 |         let tomls = (Set.fromList . toList) $ fmap (execTomlCodec codec) ((NE.fromList . Set.toList) as)
```

This failure of deducing Ord constraint does not occur for codecRead but only for CodecWrite. I wonder why. Did I go on the wrong track?

**Comment by chshersh** [comment]
@SanchayanMaity I feel like your implementation is too complicated. You should reuse `list` combinator and use `dimap` combinator to build `set` and `hashSet` combinators:

https://github.com/kowainik/tomland/blob/3c323e14e8b344c7cf2340b5ca32b44a1ab15925/src/Toml/Bi/Monad.hs#L144-L149

The only codec that should be implemented in a _dirty_ way using the internals of the TOML data type is `nonEmpty` because internally lists are represented as `NonEmpty`. And `list` combinator adds some additional logic on top of `nonEmpty` because you can't easily convert between `NonEmpty` and `[]` in both sides. But you can do this without problems for `Set` and `HashSet` using `fromList` and `toList` functions.

**Comment by SanchayanMaity** [comment]
Thank you
