### ISSUE TITLE
Implement property tests for `genericCodec`

### ISSUE THREAD

**Issue by chshersh** [kowainik/tomland#202]
I assume that tests will look like this:

1. Base tests on already existing `BigType`.
2. Add more fields to it if necessary.
3. Roundtrip property for `genericCodec` holds.
4. Implement manual codec and verify that `genericCodec` and manual codec are consistent with each other.

**Comment by bangn** [comment]
I would like to have a look at this :)

**Comment by chshersh** [comment]
@bangn Sure, go for it! Let us know if you have any questions 🙂

**Comment by Nimor111** [comment]
I'd like to work on this.

**Comment by chshersh** [comment]
@Nimor111, I've slightly changed issue description to tell some plan. The proposal is to base tests on the already existing `BigType` data type:

* https://github.com/kowainik/tomland/blob/d906bd9e6d63b8063955fa7382da6fe7f10f6461/test/Test/Toml/BiCode/Property.hs#L36

The idea is simple:

1. Derive `Generic` for this data type
2. Implement TOML codec using `genericCodec`.
3. Make sure that existing `bigTypeCodec` and new `genericBigTypeCodec` work in the same way.

I believe there shouldn't be any unexpected issues, but I might be wrong. Refer to the documentation of the `Toml.Generic` module to see how to write generic codecs. And feel free to ask any questions 🙂
