### ISSUE TITLE
Move benchmarks to separate repository

### ISSUE THREAD

**Issue by chshersh** [kowainik/tomland#215]
We have benchmarks with other TOML packages. But all of them are not maintained and are becoming more obsolete and problematic each year. It becomes much harder to maintain `tomland` and support new GHC versions... So I propose to move benchmarks to a separate GitHub repository and maintain them separately so they won't slowdown main development process. 

What do you think?

**Comment by vrom911** [comment]
Great idea! I also find it too hard to maintain because of those reasons...

**Comment by willbasky** [comment]
It needed the `toml-benchmark` repository were opened.

**Comment by chshersh** [comment]
I've created the repository:

* https://github.com/kowainik/toml-benchmarks

**Comment by kutyel** [comment]
I'll try to take this one if that's OK :)

Whenever I'm done with the other repo please remind me to create another PR in this one to remove all `benchmark` related stuff from `.cabal` etc... 😉

**Comment by chshersh** [comment]
@willbasky I think it's enough. I wrote a comment with more motivation on this earlier:

* https://github.com/kowainik/toml-benchmarks/pull/1#discussion_r331744794
