### ISSUE TITLE
Refactor `Test.Toml.Parsing.Unit`

### ISSUE THREAD

**Issue by chshersh** [kowainik/tomland#217]
587 lines for a testing file is insane. Also it's a bid hard to work with the existing tests. The following refactoring should be performed to make existing and new tests nicer:

- [ ] Use eDSL to construct test `TOML` values (we've implemented it for this purpose)
- [ ] Use `neat-interpolation` to construct testing strings where possible (or at least `unlines`/`intercalate`)
- [x] Split into multiple modules: `Test.Toml.Parser.{Unit, Unit.Boo, Unit.Integer, ...}`

Better names for testing modules are appreciated!

**Comment by Nimor111** [comment]
Hey, can I take this?

**Comment by chshersh** [comment]
@Nimor111 Hi, sure! You can take this :slightly_smiling_face: You can see that this issue contains several steps and since we have a huge test-suite, it's might be easier to write and (more importantly) easier to review, if this issue is going to be split into multiple independent PRs. For example, good first would be to do some preparation work, eg. create `Test.Toml.Parser` module with the following content:

https://github.com/kowainik/tomland/blob/80b57094613b3f6db0c742446a1555867d2f30f4/test/Test/Toml/Parsing/Unit.hs#L27-L36

And move each of these test suites into corresponding module and probably introducing some `Test.Toml.Parser.Common` module where you can put all reusable functions.Toml

After carefully reviewing current unit tests, I see that refactoring is required only for tests in `keySpecs` and `tomlSpecs` test suites. Other tests are already quite optimal in terms of how they they are written.

**Comment by Nimor111** [comment]
Thanks for the pointers ! I'll start work on the first part then.

**Comment by Nimor111** [comment]
Just a little update, i'm working on the refactoring of the Toml and Key modules ( using the edsl instead of the helper functions there and the `neat-interpolation`, going a bit slower because of work during the week and tiredness in the evening. It should be done by next weekend, hope that's not too long.

**Comment by chshersh** [comment]
@Nimor111 don't worry! I appreciate a lot your work on this issue :+1: It's definitely going to improve code quality. It's not a blocking feature, so take your time :slightly_smiling_face:
