### ISSUE TITLE
Add `disum` combinator for sum types

### ISSUE THREAD

**Issue by Nimor111** [kowainik/tomland#226]
Connected to [crocodealer/#9](https://github.com/kowainik/crocodealer/pull/9).

Since the `prism` approach for sum types works with single non-nested values, a new combinator is needed to handle sum types, similar to dimap but accounting for the fact that the value may not be there ( doesn't have the right constructor we need ). So a combinator `disum` could be added to handle that with a type of:

```haskell
disum
    :: (c -> Maybe d) -- ^ Mapper for consumer
    -> (a -> b)       -- ^ Mapper for producer
    -> Codec r w d a  -- ^ Source 'Codec' object
    -> Codec r w c b  -- ^ Target 'Codec' object
```

It's implemented in the pull request above but it would be better here. I'm willing to contribute it.

**Comment by chshersh** [comment]
@Nimor111 thank you for tracking this issue here after our discussion!
