### ISSUE TITLE
Support more `Map`-like data structures

### ISSUE THREAD

**Issue by chshersh** [kowainik/tomland#243]
Currently, there is codec only for `Map`. But it would be more useful to implement it also for:

- [ ] `HashMap`
- [ ] `IntMap`

As well as generic codecs (once #242 is resolved). The only difficulty is the sane removal of boilerplate.

**Comment by forficate** [comment]
HashMap would be useful.

Currently I'm struggling for a clean way to handle parsing tables with adhoc/dynamic paths i.e.

```
[server]

[server.a]
...

[server.b]
...

[server.c]
...

[server.*]
```

I want to parse in to a `Codec a =>  Map[Text, a]` where the key is `a`,`b,` or `c` etc.

**Comment by chshersh** [comment]
@forficate Thanks for your comment! Adding support for more Haskell data types is not that difficult, there're already examples on how to do this :slightly_smiling_face: Regarding your specific example of dynamic paths: I can see how this can be tricky. However, I think it's possible to add a few combinators to `tomland` to make decoding such things easier. I can propose you to open a separate issue where we can think and discuss the potential interface and implementation for this. I think it will be useful to support such cases in `tomland` smoothly.
