### ISSUE TITLE
Add more examples to docs

### ISSUE THREAD

**Issue by vrom911** [kowainik/tomland#245]
I would love to see the following elements for each codec:

* Corresponding Haskell data type
* Corresponding TOML file content
* bidirectional codec and how it is used in code.

**Comment by chshersh** [comment]
@vrom911 I think this issue is done as a part of #283. Should we close it? Now each module has a table with examples thanks to your effort :slightly_smiling_face:

**Comment by vrom911** [comment]
Yes! Thank you :heart:
