### ISSUE TITLE
Explicitly disclose TOML specification version implemented

### ISSUE THREAD

**Issue by szabi** [kowainik/tomland#249]
Explicitly mention the TOML specification that is implemented by `tomland` in at least both `README.md` and the `description:` stanza of the cabal file.

**Comment by chshersh** [comment]
@szabi thanks for the suggestion. A note was added to `README.md`.

**Comment by szabi** [comment]
Great, I wasn't sure.

Added `tomland` to the toml-lang/toml wiki: https://github.com/toml-lang/toml/wiki
