### ISSUE TITLE
Table Maps Codec

### ISSUE THREAD

**Issue by everythingfunctional** [kowainik/tomland#261]
This is a follow up to #254. #255 Solved the problem of dynamic keys if the values are simple values. But I need the values to be more complex than that. I need a way of specifying a codec for the values.

**Comment by everythingfunctional** [comment]
I came up with an approach in #262, but I think it's still not quite sufficient. What you'd really like to be able to specify is a codec that will work for simple values, tables or arrays, but this function so far only covers tables. I don't think the array case would be too difficult, but I'm not quite sure how to deal with the simple value case.

**Comment by chshersh** [comment]
Sharing a link to a comment that explains use-case in detail:

* https://github.com/kowainik/tomland/pull/262#issuecomment-625302500
