### ISSUE TITLE
DerivingVia for Generic table codecs

### ISSUE THREAD

**Issue by chshersh** [kowainik/tomland#272]
I've tried to use fancy tricks for table codecs with generics. You can find my commented code here:

https://github.com/kowainik/tomland/blob/536a5e6ffb148d0dd4e4c4b120913a6744097676/src/Toml/Codec/Generic.hs#L406-L449

It wasn't possible to implement this feature back then. But thanks to @vrom911 nice work on simplifying the `Codec` type, I think we should be able to implement that feature again.

**Comment by vrom911** [comment]
Currently, I am getting 
```haskell
    • Couldn't match type ‘TomlTable Address’ with ‘Address’
        arising from the coercion of the method ‘hasCodec’
          from type ‘Toml.Key -> TomlCodec (TomlTable Address)’
            to type ‘Toml.Key -> TomlCodec Address’
    • When deriving the instance for (HasCodec Address)
    |
182 |       deriving HasCodec via (TomlTable Address)
    |    
```

With the example from docs. I don't really know how to solve this issue. Do you have any ideas, @chshersh ?

**Comment by chshersh** [comment]
@vrom911 Ah, sh*t, here we go again. The error is different, but it doesn't tell me how to solve the issue. Well, I guess not in this release...

**Comment by chshersh** [comment]
I've asked on SO:

* https://stackoverflow.com/questions/61840227/cannot-coerce-data-type-with-reader-as-a-field

**Comment by chshersh** [comment]
Should be possible to do after #311 :slightly_smiling_face:
