### ISSUE TITLE
PrintOptions for lists

### ISSUE THREAD

**Issue by vrom911** [kowainik/tomland#325]
`Bool` to indicate whether to print list elements each on a separate line or all together (current version)

See use-case: https://github.com/kowainik/life-sync/pull/102#discussion_r428633721

**Comment by willbasky** [comment]
@vrom911 Hi!
Could you clarify what list the task related ? I mean how what type in tomland and how it will look like with and without flag in toml file?

**Comment by vrom911** [comment]
@willbasky , sure!
I was thinking of patching the `PrintOptions` data type: 
https://github.com/kowainik/tomland/blob/080e6720e6d0740f139408fa73e2d861e1d6c57b/src/Toml/Type/Printer.hs#L45-L57

by adding an additional field in there. That field should indicate how to pretty-print list types. Now, it would print all array elements in one line:

https://github.com/kowainik/tomland/blob/080e6720e6d0740f139408fa73e2d861e1d6c57b/src/Toml/Type/Printer.hs#L146

But with this change, lists should be outputted either like this:

```toml
foo = 
    [ a
    , b
    ]
```

or as before:

```toml
foo = [a, b]
```
