### ISSUE TITLE
[Parser] Multiline string

### ISSUE THREAD

**Issue by dariodsa** [kowainik/tomland#353]
Hi, 
I am working on an issue #334 and I during testing of my code I step upon on some TOML example.
```haskell
*Toml> Toml.encode (Toml.text "a") "\n"
"a = \"\\n\"\n"
```
This string is a multiline string and it should be followed and ended with triple quotes so I think that this shouldn't be parsed in TOML object.  I don't am I missing anything with this example.

**Comment by chshersh** [comment]
@dariodsa The string you see is actually the result of applying `Show` instance to `Text`. If you print it to terminal, the TOML will look like this:

```haskell
ghci> putStrLn "a = \"\\n\"\n"
a = "\n"
```

The TOML spec allows using escaped sequences in ordinary strings, including the `\n` symbol:

* https://toml.io/en/v1.0.0-rc.3#string

I think there exist multiple ways to format a string, but implementing those ways would complicate the logic significantly, so I think it's okay to have the single working version of encoding of strings 🙂
