### ISSUE TITLE
Failing build on Hackage

### ISSUE THREAD

**Issue by gregorias** [kowainik/tomland#387]
[My package on Hackage which depends on tomland doesn't build properly](https://hackage.haskell.org/package/forex2ledger-1.0.0.2/reports/2) due to tomland failing:

```
Linking dist/build/play-tomland/play-tomland ...
Preprocessing executable 'readme' for tomland-1.3.3.0..
Building executable 'readme' for tomland-1.3.3.0..
ghc: could not execute: markdown-unlit
```

I see that [you had similar problems in the past](https://hackage.haskell.org/package/tomland-1.0.0/reports/3). Do you know if this is something that can be fixed in tomland or is this something that I have to address in my package?

**Comment by vrom911** [comment]
Hi @gregorias !

Yes, this is a known issue on Hackage. If you look at the Hackage matrix you'll see that's everything is fine with your package: https://matrix.hackage.haskell.org/#/package/forex2ledger
The downside of this weird behaviour is that docs are not built automatically for you. But you still can upload it manually. For that you can use the following:

```
$ cabal haddock --enable-documentation --haddock-for-hackage
```

This will finish with the link to the created tar. use path to it as the argument to this command:

```
cabal upload -d PATH_TO_TAR --publish
```

Enter your credentials and that's all.

Hope this helps.

**Comment by gregorias** [comment]
I see, thank you for explaining how I could fix lack of docs with cabal.
