### ISSUE TITLE
Compatibility with GHC 9.4

### ISSUE THREAD

**Issue by sjakobi** [kowainik/tomland#412]
Could you please make a compatible release? :)

**Comment by Qqwy** [comment]
For the time being you might have some luck with the fork/pull request branch https://github.com/kowainik/tomland/pull/409 which brings `base` up to date for at least GHC 9.2.x (I'm not sure if this is enough for GHC 9.4.x but it might be a start.)

---

This would be a very welcome change in my opinion!

**Comment by Qqwy** [comment]
@vrom911 Any progress?
