### ISSUE TITLE
Support GHC 9.6

### ISSUE THREAD

**Issue by tfausak** [kowainik/tomland#424]
https://discourse.haskell.org/t/ghc-9-6-1-is-now-available/5972

**Comment by tfausak** [comment]
Blocked by https://github.com/kowainik/validation-selective/issues/76, which would be fixed by either https://github.com/kowainik/validation-selective/pull/69 or https://github.com/kowainik/validation-selective/pull/77.

**Comment by tomjaguarpaw** [comment]
This is resolved (by https://github.com/kowainik/tomland/issues/427#issuecomment-1668041658)
