### ISSUE TITLE
Please make Hackage revision

### ISSUE THREAD

**Issue by tomjaguarpaw** [kowainik/tomland#427]
Could you please bump the base version dependency on Hackage to `< 4.18` for `tomland`? It works fine with GHC 9.4 at least without change (I haven't tried 9.6).

**Comment by tomjaguarpaw** [comment]
I can confirm 9.6 is fine too, so the bound can be `base < 4.19`.

**Comment by tomjaguarpaw** [comment]
Specifically, `tomland-1.3.3.1` can be expanded to `base < 4.19`.

**Comment by andreasabel** [comment]
https://hackage.haskell.org/package/tomland-1.3.3.2/revisions/

I tested the revision with GHC 9.6.2 and 9.4.5.
