### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by telser** [kowainik/tomland#443]
Would the maintainers here be open to adding this library to stackage? Asked the same of `validation-selective` [here](https://github.com/kowainik/validation-selective/issues/88) which I believe, by my usage, would be the only blocker for this library.

**Comment by tomjaguarpaw** [comment]
If you want to take responsibility for it on Stackage then be my guest!

**Comment by telser** [comment]
@tomjaguarpaw Could you create a release that includes `0f107269b8835a8253f618b75930b11d3a3f1337` ? That is my current blocker to adding to stackage.

**Comment by tomjaguarpaw** [comment]
Sure, here: https://hackage.haskell.org/package/tomland-1.3.3.3

**Comment by telser** [comment]
Closing, since stackage PR is open now. Thank you again for everything!

**Comment by tomjaguarpaw** [comment]
You're welcome!
