### ISSUE TITLE
Write 'doctest' tests

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#68]
Okay, so I want to put every testcase from [TOML](https://github.com/toml-lang/toml) specification into our documentation and test them all with `doctest`. Once we figure out how to do it in neat way, we can implement those tests and use `doctest` for them.

**Comment by astynax** [comment]
I think that #103 could solve this issue for the pretty printer case at least.

**Comment by ChShersh** [comment]
After #103 is merged, I actually can't tell what we can test with `doctest` in our code. Probably there're some things to keep some pieces of documentation up-to-date (so I will leave this issue open). But regarding tests from TOML specification: I think they can just be a subset of our extensive unit testing test suite:

* https://github.com/kowainik/tomland/blob/master/test/Test/Toml/Parsing/Unit.hs

**Comment by ChShersh** [comment]
Not sure we need `doctest` in this package, we have a lot of other tests... Closing for now, since I don't see possible tests for them.
