### ISSUE TITLE
Add easier way to write custom `BiMap` for values

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#70]
If I have custom data type with couple functions like this one:

```haskell
data GhcVer = ...

showGhcVer  :: GhcVer -> Text
parseGhcVer :: Text -> Maybe GhcVer
```

Then writing custom `BiMap` for this data type is a little bit tedious:

```haskell
    _GhcVer :: BiMap AnyValue GhcVer
    _GhcVer = BiMap
        { forward = \(AnyValue t) -> Toml.matchText t >>= parseGhcVer
        , backward = Just . AnyValue . Toml.Text . showGhcVer
        }
```

I want easier way to write such prisms.

**Comment by jiegillet** [comment]
If you mean something like
```
toBiMap :: (a -> Text) -> (Text -> Maybe a) -> BiMap AnyValue a
toBiMap showA parseA = BiMap
        { forward = \(AnyValue t) -> Toml.matchText t >>= parseA
        , backward = Just . AnyValue . Toml.Text . showA
        }
```
I'd be happy to add it!

**Comment by ChShersh** [comment]
@jiegillet This is good start! But I would like to have more generic solution, that can work not only with `Text` constructor of `Value` data type. Having function with type `(a -> Text) -> (Text -> Maybe a) -> BiMap AnyValue a` is already useful, but I guess it should have more specific name rather than `toBiMap`. Probably `textValBiMap` or something like that.

**Comment by ChShersh** [comment]
Done in #104
