### ISSUE TITLE
Improve 'AnyValue' generator for property-based tests

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#72]
I'm talking about this generator:

https://github.com/kowainik/tomland/blob/6c60b40b0991faa8e1f6d561662e467228d516fa/test/Test/Toml/Gen.hs#L52-L64

Currently it doesn't generate everything we can parse. This generator should be expanded with the following:

- [x] `nan` and `inf` to double generator
- [x] Arrays
- [x] Different types of text after supporting string parser
- [x] Dates (after they're supported)

**Comment by willbasky** [comment]
> nan and inf to double generator

What is it? Does they supported?

> Different types of text after supporting string parser
what is different types? Is it supported already?

> Dates (after they're supported)
It is in many places. Is it completely supported?

**Comment by ChShersh** [comment]
> What is it? Does they supported?

`Nan` and `Infitity` are special double values. Check this `Double` parser to see how they are represented in Haskell:

https://github.com/kowainik/tomland/blob/e33524f1d299a38e0ceabfba628b7e27763977d8/src/Toml/Parser.hs#L174-L180

> what is different types? Is it supported already?

Currently randomly generated text contains only alphanumeric characters. But in reality it also can contain some unicode characters and newline breaks and much more. See `Text` parser for all possible cases.

> t is in many places. Is it completely supported?

Yes, dates should be completely supported after @ghallak PR. So you need to generate value of this type:

https://github.com/kowainik/tomland/blob/e33524f1d299a38e0ceabfba628b7e27763977d8/src/Toml/Type/Value.hs#L141

**Comment by ChShersh** [comment]
Thanks to @willbasky! This is fixed now as well.
