### ISSUE TITLE
Remove `maybeT` in favour of `dioptional`

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#82]
See here:

https://github.com/kowainik/summoner/blob/master/src/Summoner/Config.hs#L165-L169

**Comment by willbasky** [comment]
What is `dioptional`?
Link points to 
```
lastT :: (Key -> BiToml a) -> Key -> BiToml (Last a)
lastT = Toml.wrapper . Toml.maybeT
```
the function uses `maybeT` self.

**Comment by ChShersh** [comment]
@willbasky Sorry, link is wrong. It should be with commit. Look at `dimaybeT`. This function should convert `BiCodec a` to `BiCodec (Maybe a)`

**Comment by willbasky** [comment]
> This function should convert BiCodec a to BiCodec (Maybe a)

Do you mean `TomlCodec a -> TomlCodec (Maybe a)`?
as it is in `maybeT :: forall a . (Key -> TomlCodec a) -> Key -> TomlCodec (Maybe a)`

**Comment by willbasky** [comment]
And **why** change `maybeT` with `dimaybeT`?

**Comment by ChShersh** [comment]
> Do you mean TomlCodec a -> TomlCodec (Maybe a)?

No, this function should be general and work for `BiCodec`

https://github.com/kowainik/tomland/blob/d1720a08534482527b63dff6474d4ac84bc73dcb/src/Toml/Bi/Monad.hs#L47

> And why change maybeT with dimaybeT?

`maybeT` is wrong an it often happens that `maybeT` doesn't work as expected. So `maybeT` should be removed. So I want to have something like `optional` for `Alternative` for our our `Codec`. Unfortunately, `optional` for `Codec` works in the following way:

```haskell
optional :: Codec r w a b -> Codec r w a (Maybe b)`
```

while I want:

```haskell
dioptional :: Codec r w a b -> Codec r w (Maybe a) (Maybe b)
```

If you can write `dioptional` for `Codec` instead of `BiCodec`, it would be even better :+1:

**Comment by ChShersh** [comment]
@willbasky Yeah, types were renamed in some recent PR. And the new version is not on Hackage yet.

**Comment by willbasky** [comment]
Does `dimaybeT` something like workaround?

**Comment by ChShersh** [comment]
Yes, it is. After `dioptional` is implemented in `tomland`, it will replace `dimaybeT` in `summoner`
