### ISSUE TITLE
Split `Toml.Parser` file into smaller files

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#99]
This file is pretty big and takes a lot of time to compile, unfortunately. So this is the moment where it should be split into smaller files. I imagine the following hierarchy:

1. `Toml.Parser.Core`: basic general purpose combinators under `Library for parsing ` section
2. `Toml.Parser.Value`: `valueP` parser and [all parsers required for `valueP`](https://github.com/kowainik/tomland/blob/9d114b5d91bfd6f8650a9296c22970525cdf30a5/src/Toml/Parser.hs#L269-L275)
3. `Toml.Parser.TOML`: all parsers for TOML data type
4. `Toml.Parser`: `ParseException` data type and `parse` function.

**Comment by MorrisLaw** [comment]
Can I take this?

**Comment by vrom911** [comment]
@MorrisLaw go ahead!

**Comment by ChShersh** [comment]
@gahag Sure, you can work on this!

**Comment by MorrisLaw** [comment]
Yes, I haven't had time to really dive in. Go for it @gahag
